import Foundation
import Testing
@testable import Hebcal

// Expected values were generated by the KosherJava Zmanim API
// (com.kosherjava.zmanim.AstronomicalCalendar with its default NOAACalculator),
// which this Swift implementation is ported from.
struct NOAACalculatorTests {

    let iso: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()

    func assertInstant(_ actual: Date?, _ expected: String, sourceLocation: SourceLocation = #_sourceLocation) {
        guard let actual = actual else {
            Issue.record("Expected \(expected), got nil", sourceLocation: sourceLocation)
            return
        }
        let expectedDate = iso.date(from: expected)!
        #expect(Swift.abs(actual.timeIntervalSince(expectedDate)) <= 0.01,
                "Actual: \(iso.string(from: actual)), Expected: \(expected)", sourceLocation: sourceLocation)
    }

    func makeCalendar(_ lat: Double, _ lon: Double, elevation: Double = 0, _ tzid: String, _ y: Int, _ m: Int, _ d: Int) -> AstronomicalCalendar {
        let geo = GeoLocation(latitude: lat, longitude: lon, elevation: elevation, timeZone: TimeZone(identifier: tzid)!)
        return AstronomicalCalendar(geoLocation: geo, localDate: LocalDate(year: y, month: m, day: d))
    }

    @Test func newYork() {
        let cal = makeCalendar(40.7128, -74.0060, "America/New_York", 2023, 12, 1)
        assertInstant(cal.getSunrise(), "2023-12-01T12:00:26.622Z")
        assertInstant(cal.getSunset(), "2023-12-01T21:29:21.467Z")
        assertInstant(cal.getSunTransit(), "2023-12-01T16:45:01.673Z")
        assertInstant(cal.getSunsetOffsetByDegrees(98.5), "2023-12-01T22:14:01.435Z")
    }

    @Test func jerusalemWithElevation() {
        let cal = makeCalendar(31.7683, 35.2137, elevation: 800, "Asia/Jerusalem", 2023, 12, 1)
        assertInstant(cal.getSunrise(), "2023-12-01T04:16:05.811Z")
        assertInstant(cal.getSunset(), "2023-12-01T14:39:46.821Z")
        assertInstant(cal.getSeaLevelSunset(), "2023-12-01T14:35:03.931Z")
        assertInstant(cal.getSunTransit(), "2023-12-01T09:28:02.130Z")
        // Elevation only adjusts sunrise and sunset, not degree-based times
        assertInstant(cal.getSunsetOffsetByDegrees(98.5), "2023-12-01T15:14:12.391Z")
    }

    @Test func antimeridianApia() {
        // Samoa is UTC+13 but west of the antimeridian; times must fall on the local date
        let cal = makeCalendar(-13.8333, -171.7667, "Pacific/Apia", 2023, 6, 15)
        assertInstant(cal.getSunrise(), "2023-06-14T17:47:56.906Z")
        assertInstant(cal.getSunset(), "2023-06-15T05:06:51.236Z")
        assertInstant(cal.getSunTransit(), "2023-06-14T23:27:24.807Z")
        assertInstant(cal.getSunsetOffsetByDegrees(98.5), "2023-06-15T05:41:09.572Z")
    }

    @Test func polarDay() {
        let cal = makeCalendar(82.5, -62.35, "America/Toronto", 2023, 6, 1)
        #expect(cal.getSunrise() == nil)
        #expect(cal.getSunset() == nil)
        #expect(cal.getSunsetOffsetByDegrees(98.5) == nil)
        assertInstant(cal.getSunTransit(), "2023-06-01T16:07:14.743Z")
    }

    @Test func solarElevationAzimuth() {
        let calc = NOAACalculator()
        let geo = GeoLocation(latitude: 40.7128, longitude: -74.0060, timeZone: TimeZone(identifier: "America/New_York")!)
        let instant = iso.date(from: "2023-12-01T17:00:00.000Z")!
        #expect(Swift.abs(calc.getSolarElevation(instant, geo) - 27.38736339830967) <= 1e-9)
        #expect(Swift.abs(calc.getSolarAzimuth(instant, geo) - 183.91124038784403) <= 1e-9)
    }

    @Test func apparentSolarRadius() {
        let calc = NOAACalculator()
        #expect(calc.getApparentSolarRadius(LocalDate(year: 2024, month: 1, day: 1)) == 0.27108024)
        #expect(calc.getApparentSolarRadius(LocalDate(year: 2024, month: 2, day: 29)) == calc.getApparentSolarRadius(LocalDate(year: 2024, month: 2, day: 28)))
        #expect(calc.getApparentSolarRadius(LocalDate(year: 2024, month: 12, day: 31)) == 0.27108399)
        #expect(calc.getApparentSolarRadius(nil) == 16 / 60.0)

        var fixed = NOAACalculator()
        fixed.solarRadius = 16 / 60.0
        #expect(!fixed.useApparentSolarRadius)
    }
}
