import Foundation
import Testing
@testable import Hebcal

/// Expected values for Omer days 1–49, generated from OmerEvent in @hebcal/core.
/// `.heNikud` corresponds to the `he` locale there, and `.he` to `he-x-NoNikud`.
enum OmerFixtures {
    /// `render(lang: .en)`
    static let en: [String] = [
        "1st day of the Omer",
        "2nd day of the Omer",
        "3rd day of the Omer",
        "4th day of the Omer",
        "5th day of the Omer",
        "6th day of the Omer",
        "7th day of the Omer",
        "8th day of the Omer",
        "9th day of the Omer",
        "10th day of the Omer",
        "11th day of the Omer",
        "12th day of the Omer",
        "13th day of the Omer",
        "14th day of the Omer",
        "15th day of the Omer",
        "16th day of the Omer",
        "17th day of the Omer",
        "18th day of the Omer",
        "19th day of the Omer",
        "20th day of the Omer",
        "21st day of the Omer",
        "22nd day of the Omer",
        "23rd day of the Omer",
        "24th day of the Omer",
        "25th day of the Omer",
        "26th day of the Omer",
        "27th day of the Omer",
        "28th day of the Omer",
        "29th day of the Omer",
        "30th day of the Omer",
        "31st day of the Omer",
        "32nd day of the Omer",
        "33rd day of the Omer",
        "34th day of the Omer",
        "35th day of the Omer",
        "36th day of the Omer",
        "37th day of the Omer",
        "38th day of the Omer",
        "39th day of the Omer",
        "40th day of the Omer",
        "41st day of the Omer",
        "42nd day of the Omer",
        "43rd day of the Omer",
        "44th day of the Omer",
        "45th day of the Omer",
        "46th day of the Omer",
        "47th day of the Omer",
        "48th day of the Omer",
        "49th day of the Omer",
    ]
    /// `render(lang: .heNikud)`
    static let he: [String] = [
        "א׳ בָּעוֹמֶר",
        "ב׳ בָּעוֹמֶר",
        "ג׳ בָּעוֹמֶר",
        "ד׳ בָּעוֹמֶר",
        "ה׳ בָּעוֹמֶר",
        "ו׳ בָּעוֹמֶר",
        "ז׳ בָּעוֹמֶר",
        "ח׳ בָּעוֹמֶר",
        "ט׳ בָּעוֹמֶר",
        "י׳ בָּעוֹמֶר",
        "י״א בָּעוֹמֶר",
        "י״ב בָּעוֹמֶר",
        "י״ג בָּעוֹמֶר",
        "י״ד בָּעוֹמֶר",
        "ט״ו בָּעוֹמֶר",
        "ט״ז בָּעוֹמֶר",
        "י״ז בָּעוֹמֶר",
        "י״ח בָּעוֹמֶר",
        "י״ט בָּעוֹמֶר",
        "כ׳ בָּעוֹמֶר",
        "כ״א בָּעוֹמֶר",
        "כ״ב בָּעוֹמֶר",
        "כ״ג בָּעוֹמֶר",
        "כ״ד בָּעוֹמֶר",
        "כ״ה בָּעוֹמֶר",
        "כ״ו בָּעוֹמֶר",
        "כ״ז בָּעוֹמֶר",
        "כ״ח בָּעוֹמֶר",
        "כ״ט בָּעוֹמֶר",
        "ל׳ בָּעוֹמֶר",
        "ל״א בָּעוֹמֶר",
        "ל״ב בָּעוֹמֶר",
        "ל״ג בָּעוֹמֶר",
        "ל״ד בָּעוֹמֶר",
        "ל״ה בָּעוֹמֶר",
        "ל״ו בָּעוֹמֶר",
        "ל״ז בָּעוֹמֶר",
        "ל״ח בָּעוֹמֶר",
        "ל״ט בָּעוֹמֶר",
        "מ׳ בָּעוֹמֶר",
        "מ״א בָּעוֹמֶר",
        "מ״ב בָּעוֹמֶר",
        "מ״ג בָּעוֹמֶר",
        "מ״ד בָּעוֹמֶר",
        "מ״ה בָּעוֹמֶר",
        "מ״ו בָּעוֹמֶר",
        "מ״ז בָּעוֹמֶר",
        "מ״ח בָּעוֹמֶר",
        "מ״ט בָּעוֹמֶר",
    ]
    /// `render(lang: .he)`
    static let heNoNikud: [String] = [
        "א׳ בעומר",
        "ב׳ בעומר",
        "ג׳ בעומר",
        "ד׳ בעומר",
        "ה׳ בעומר",
        "ו׳ בעומר",
        "ז׳ בעומר",
        "ח׳ בעומר",
        "ט׳ בעומר",
        "י׳ בעומר",
        "י״א בעומר",
        "י״ב בעומר",
        "י״ג בעומר",
        "י״ד בעומר",
        "ט״ו בעומר",
        "ט״ז בעומר",
        "י״ז בעומר",
        "י״ח בעומר",
        "י״ט בעומר",
        "כ׳ בעומר",
        "כ״א בעומר",
        "כ״ב בעומר",
        "כ״ג בעומר",
        "כ״ד בעומר",
        "כ״ה בעומר",
        "כ״ו בעומר",
        "כ״ז בעומר",
        "כ״ח בעומר",
        "כ״ט בעומר",
        "ל׳ בעומר",
        "ל״א בעומר",
        "ל״ב בעומר",
        "ל״ג בעומר",
        "ל״ד בעומר",
        "ל״ה בעומר",
        "ל״ו בעומר",
        "ל״ז בעומר",
        "ל״ח בעומר",
        "ל״ט בעומר",
        "מ׳ בעומר",
        "מ״א בעומר",
        "מ״ב בעומר",
        "מ״ג בעומר",
        "מ״ד בעומר",
        "מ״ה בעומר",
        "מ״ו בעומר",
        "מ״ז בעומר",
        "מ״ח בעומר",
        "מ״ט בעומר",
    ]
    /// `renderBrief(lang: .en)`
    static let brief: [String] = [
        "Omer day 1",
        "Omer day 2",
        "Omer day 3",
        "Omer day 4",
        "Omer day 5",
        "Omer day 6",
        "Omer day 7",
        "Omer day 8",
        "Omer day 9",
        "Omer day 10",
        "Omer day 11",
        "Omer day 12",
        "Omer day 13",
        "Omer day 14",
        "Omer day 15",
        "Omer day 16",
        "Omer day 17",
        "Omer day 18",
        "Omer day 19",
        "Omer day 20",
        "Omer day 21",
        "Omer day 22",
        "Omer day 23",
        "Omer day 24",
        "Omer day 25",
        "Omer day 26",
        "Omer day 27",
        "Omer day 28",
        "Omer day 29",
        "Omer day 30",
        "Omer day 31",
        "Omer day 32",
        "Omer day 33",
        "Omer day 34",
        "Omer day 35",
        "Omer day 36",
        "Omer day 37",
        "Omer day 38",
        "Omer day 39",
        "Omer day 40",
        "Omer day 41",
        "Omer day 42",
        "Omer day 43",
        "Omer day 44",
        "Omer day 45",
        "Omer day 46",
        "Omer day 47",
        "Omer day 48",
        "Omer day 49",
    ]
    /// `renderBrief(lang: .heNikud)`
    static let briefHe: [String] = [
        "עוֹמֶר יוֹם 1",
        "עוֹמֶר יוֹם 2",
        "עוֹמֶר יוֹם 3",
        "עוֹמֶר יוֹם 4",
        "עוֹמֶר יוֹם 5",
        "עוֹמֶר יוֹם 6",
        "עוֹמֶר יוֹם 7",
        "עוֹמֶר יוֹם 8",
        "עוֹמֶר יוֹם 9",
        "עוֹמֶר יוֹם 10",
        "עוֹמֶר יוֹם 11",
        "עוֹמֶר יוֹם 12",
        "עוֹמֶר יוֹם 13",
        "עוֹמֶר יוֹם 14",
        "עוֹמֶר יוֹם 15",
        "עוֹמֶר יוֹם 16",
        "עוֹמֶר יוֹם 17",
        "עוֹמֶר יוֹם 18",
        "עוֹמֶר יוֹם 19",
        "עוֹמֶר יוֹם 20",
        "עוֹמֶר יוֹם 21",
        "עוֹמֶר יוֹם 22",
        "עוֹמֶר יוֹם 23",
        "עוֹמֶר יוֹם 24",
        "עוֹמֶר יוֹם 25",
        "עוֹמֶר יוֹם 26",
        "עוֹמֶר יוֹם 27",
        "עוֹמֶר יוֹם 28",
        "עוֹמֶר יוֹם 29",
        "עוֹמֶר יוֹם 30",
        "עוֹמֶר יוֹם 31",
        "עוֹמֶר יוֹם 32",
        "עוֹמֶר יוֹם 33",
        "עוֹמֶר יוֹם 34",
        "עוֹמֶר יוֹם 35",
        "עוֹמֶר יוֹם 36",
        "עוֹמֶר יוֹם 37",
        "עוֹמֶר יוֹם 38",
        "עוֹמֶר יוֹם 39",
        "עוֹמֶר יוֹם 40",
        "עוֹמֶר יוֹם 41",
        "עוֹמֶר יוֹם 42",
        "עוֹמֶר יוֹם 43",
        "עוֹמֶר יוֹם 44",
        "עוֹמֶר יוֹם 45",
        "עוֹמֶר יוֹם 46",
        "עוֹמֶר יוֹם 47",
        "עוֹמֶר יוֹם 48",
        "עוֹמֶר יוֹם 49",
    ]
    /// `renderBrief(lang: .he)`
    static let briefHeNN: [String] = [
        "עומר יום 1",
        "עומר יום 2",
        "עומר יום 3",
        "עומר יום 4",
        "עומר יום 5",
        "עומר יום 6",
        "עומר יום 7",
        "עומר יום 8",
        "עומר יום 9",
        "עומר יום 10",
        "עומר יום 11",
        "עומר יום 12",
        "עומר יום 13",
        "עומר יום 14",
        "עומר יום 15",
        "עומר יום 16",
        "עומר יום 17",
        "עומר יום 18",
        "עומר יום 19",
        "עומר יום 20",
        "עומר יום 21",
        "עומר יום 22",
        "עומר יום 23",
        "עומר יום 24",
        "עומר יום 25",
        "עומר יום 26",
        "עומר יום 27",
        "עומר יום 28",
        "עומר יום 29",
        "עומר יום 30",
        "עומר יום 31",
        "עומר יום 32",
        "עומר יום 33",
        "עומר יום 34",
        "עומר יום 35",
        "עומר יום 36",
        "עומר יום 37",
        "עומר יום 38",
        "עומר יום 39",
        "עומר יום 40",
        "עומר יום 41",
        "עומר יום 42",
        "עומר יום 43",
        "עומר יום 44",
        "עומר יום 45",
        "עומר יום 46",
        "עומר יום 47",
        "עומר יום 48",
        "עומר יום 49",
    ]
    /// `sefira(lang: .en)`
    static let sefEn: [String] = [
        "Lovingkindness within Lovingkindness",
        "Might within Lovingkindness",
        "Beauty within Lovingkindness",
        "Eternity within Lovingkindness",
        "Splendor within Lovingkindness",
        "Foundation within Lovingkindness",
        "Majesty within Lovingkindness",
        "Lovingkindness within Might",
        "Might within Might",
        "Beauty within Might",
        "Eternity within Might",
        "Splendor within Might",
        "Foundation within Might",
        "Majesty within Might",
        "Lovingkindness within Beauty",
        "Might within Beauty",
        "Beauty within Beauty",
        "Eternity within Beauty",
        "Splendor within Beauty",
        "Foundation within Beauty",
        "Majesty within Beauty",
        "Lovingkindness within Eternity",
        "Might within Eternity",
        "Beauty within Eternity",
        "Eternity within Eternity",
        "Splendor within Eternity",
        "Foundation within Eternity",
        "Majesty within Eternity",
        "Lovingkindness within Splendor",
        "Might within Splendor",
        "Beauty within Splendor",
        "Eternity within Splendor",
        "Splendor within Splendor",
        "Foundation within Splendor",
        "Majesty within Splendor",
        "Lovingkindness within Foundation",
        "Might within Foundation",
        "Beauty within Foundation",
        "Eternity within Foundation",
        "Splendor within Foundation",
        "Foundation within Foundation",
        "Majesty within Foundation",
        "Lovingkindness within Majesty",
        "Might within Majesty",
        "Beauty within Majesty",
        "Eternity within Majesty",
        "Splendor within Majesty",
        "Foundation within Majesty",
        "Majesty within Majesty",
    ]
    /// `sefira(lang: .he)`
    static let sefHe: [String] = [
        "חֶֽסֶד שֶׁבְּחֶֽסֶד",
        "גְּבוּרָה שֶׁבְּחֶֽסֶד",
        "תִּפְאֶֽרֶת שֶׁבְּחֶֽסֶד",
        "נֶּֽצַח שֶׁבְּחֶֽסֶד",
        "הוֹד שֶׁבְּחֶֽסֶד",
        "יְּסוֹד שֶׁבְּחֶֽסֶד",
        "מַלְכוּת שֶׁבְּחֶֽסֶד",
        "חֶֽסֶד שֶׁבִּגְבוּרָה",
        "גְּבוּרָה שֶׁבִּגְבוּרָה",
        "תִּפְאֶֽרֶת שֶׁבִּגְבוּרָה",
        "נֶּֽצַח שֶׁבִּגְבוּרָה",
        "הוֹד שֶׁבִּגְבוּרָה",
        "יְּסוֹד שֶׁבִּגְבוּרָה",
        "מַלְכוּת שֶׁבִּגְבוּרָה",
        "חֶֽסֶד שֶׁבְּתִפְאֶֽרֶת",
        "גְּבוּרָה שֶׁבְּתִפְאֶֽרֶת",
        "תִּפְאֶֽרֶת שֶׁבְּתִפְאֶֽרֶת",
        "נֶּֽצַח שֶׁבְּתִפְאֶֽרֶת",
        "הוֹד שֶׁבְּתִפְאֶֽרֶת",
        "יְּסוֹד שֶׁבְּתִפְאֶֽרֶת",
        "מַלְכוּת שֶׁבְּתִפְאֶֽרֶת",
        "חֶֽסֶד שֶׁבְּנֶֽצַח",
        "גְּבוּרָה שֶׁבְּנֶֽצַח",
        "תִּפְאֶֽרֶת שֶׁבְּנֶֽצַח",
        "נֶּֽצַח שֶׁבְּנֶֽצַח",
        "הוֹד שֶׁבְּנֶֽצַח",
        "יְּסוֹד שֶׁבְּנֶֽצַח",
        "מַלְכוּת שֶׁבְּנֶֽצַח",
        "חֶֽסֶד שֶׁבְּהוֹד",
        "גְּבוּרָה שֶׁבְּהוֹד",
        "תִּפְאֶֽרֶת שֶׁבְּהוֹד",
        "נֶּֽצַח שֶׁבְּהוֹד",
        "הוֹד שֶׁבְּהוֹד",
        "יְּסוֹד שֶׁבְּהוֹד",
        "מַלְכוּת שֶׁבְּהוֹד",
        "חֶֽסֶד שֶׁבִּיְסוֹד",
        "גְּבוּרָה שֶׁבִּיְסוֹד",
        "תִּפְאֶֽרֶת שֶׁבִּיְסוֹד",
        "נֶּֽצַח שֶׁבִּיְסוֹד",
        "הוֹד שֶׁבִּיְסוֹד",
        "יְּסוֹד שֶׁבִּיְסוֹד",
        "מַלְכוּת שֶׁבִּיְסוֹד",
        "חֶֽסֶד שֶׁבְּמַלְכוּת",
        "גְּבוּרָה שֶׁבְּמַלְכוּת",
        "תִּפְאֶֽרֶת שֶׁבְּמַלְכוּת",
        "נֶּֽצַח שֶׁבְּמַלְכוּת",
        "הוֹד שֶׁבְּמַלְכוּת",
        "יְּסוֹד שֶׁבְּמַלְכוּת",
        "מַלְכוּת שֶׁבְּמַלְכוּת",
    ]
    /// `sefira(lang: .translit)`
    static let sefTr: [String] = [
        "Chesed sheb'Chesed",
        "Gevurah sheb'Chesed",
        "Tiferet sheb'Chesed",
        "Netzach sheb'Chesed",
        "Hod sheb'Chesed",
        "Yesod sheb'Chesed",
        "Malkhut sheb'Chesed",
        "Chesed shebiGevurah",
        "Gevurah shebiGevurah",
        "Tiferet shebiGevurah",
        "Netzach shebiGevurah",
        "Hod shebiGevurah",
        "Yesod shebiGevurah",
        "Malkhut shebiGevurah",
        "Chesed sheb'Tiferet",
        "Gevurah sheb'Tiferet",
        "Tiferet sheb'Tiferet",
        "Netzach sheb'Tiferet",
        "Hod sheb'Tiferet",
        "Yesod sheb'Tiferet",
        "Malkhut sheb'Tiferet",
        "Chesed sheb'Netzach",
        "Gevurah sheb'Netzach",
        "Tiferet sheb'Netzach",
        "Netzach sheb'Netzach",
        "Hod sheb'Netzach",
        "Yesod sheb'Netzach",
        "Malkhut sheb'Netzach",
        "Chesed sheb'Hod",
        "Gevurah sheb'Hod",
        "Tiferet sheb'Hod",
        "Netzach sheb'Hod",
        "Hod sheb'Hod",
        "Yesod sheb'Hod",
        "Malkhut sheb'Hod",
        "Chesed shebiYesod",
        "Gevurah shebiYesod",
        "Tiferet shebiYesod",
        "Netzach shebiYesod",
        "Hod shebiYesod",
        "Yesod shebiYesod",
        "Malkhut shebiYesod",
        "Chesed sheb'Malkhut",
        "Gevurah sheb'Malkhut",
        "Tiferet sheb'Malkhut",
        "Netzach sheb'Malkhut",
        "Hod sheb'Malkhut",
        "Yesod sheb'Malkhut",
        "Malkhut sheb'Malkhut",
    ]
    /// `getTodayIs(lang: .en)`
    static let todayEn: [String] = [
        "Today is 1 day of the Omer",
        "Today is 2 days of the Omer",
        "Today is 3 days of the Omer",
        "Today is 4 days of the Omer",
        "Today is 5 days of the Omer",
        "Today is 6 days of the Omer",
        "Today is 7 days, which are 1 week of the Omer",
        "Today is 8 days, which are 1 week and 1 day of the Omer",
        "Today is 9 days, which are 1 week and 2 days of the Omer",
        "Today is 10 days, which are 1 week and 3 days of the Omer",
        "Today is 11 days, which are 1 week and 4 days of the Omer",
        "Today is 12 days, which are 1 week and 5 days of the Omer",
        "Today is 13 days, which are 1 week and 6 days of the Omer",
        "Today is 14 days, which are 2 weeks of the Omer",
        "Today is 15 days, which are 2 weeks and 1 day of the Omer",
        "Today is 16 days, which are 2 weeks and 2 days of the Omer",
        "Today is 17 days, which are 2 weeks and 3 days of the Omer",
        "Today is 18 days, which are 2 weeks and 4 days of the Omer",
        "Today is 19 days, which are 2 weeks and 5 days of the Omer",
        "Today is 20 days, which are 2 weeks and 6 days of the Omer",
        "Today is 21 days, which are 3 weeks of the Omer",
        "Today is 22 days, which are 3 weeks and 1 day of the Omer",
        "Today is 23 days, which are 3 weeks and 2 days of the Omer",
        "Today is 24 days, which are 3 weeks and 3 days of the Omer",
        "Today is 25 days, which are 3 weeks and 4 days of the Omer",
        "Today is 26 days, which are 3 weeks and 5 days of the Omer",
        "Today is 27 days, which are 3 weeks and 6 days of the Omer",
        "Today is 28 days, which are 4 weeks of the Omer",
        "Today is 29 days, which are 4 weeks and 1 day of the Omer",
        "Today is 30 days, which are 4 weeks and 2 days of the Omer",
        "Today is 31 days, which are 4 weeks and 3 days of the Omer",
        "Today is 32 days, which are 4 weeks and 4 days of the Omer",
        "Today is 33 days, which are 4 weeks and 5 days of the Omer",
        "Today is 34 days, which are 4 weeks and 6 days of the Omer",
        "Today is 35 days, which are 5 weeks of the Omer",
        "Today is 36 days, which are 5 weeks and 1 day of the Omer",
        "Today is 37 days, which are 5 weeks and 2 days of the Omer",
        "Today is 38 days, which are 5 weeks and 3 days of the Omer",
        "Today is 39 days, which are 5 weeks and 4 days of the Omer",
        "Today is 40 days, which are 5 weeks and 5 days of the Omer",
        "Today is 41 days, which are 5 weeks and 6 days of the Omer",
        "Today is 42 days, which are 6 weeks of the Omer",
        "Today is 43 days, which are 6 weeks and 1 day of the Omer",
        "Today is 44 days, which are 6 weeks and 2 days of the Omer",
        "Today is 45 days, which are 6 weeks and 3 days of the Omer",
        "Today is 46 days, which are 6 weeks and 4 days of the Omer",
        "Today is 47 days, which are 6 weeks and 5 days of the Omer",
        "Today is 48 days, which are 6 weeks and 6 days of the Omer",
        "Today is 49 days, which are 7 weeks of the Omer",
    ]
    /// `getTodayIs(lang: .heNikud)`
    static let todayHe: [String] = [
        "הַיּוֹם יוֹם אֶחָד לָעֽוֹמֶר",
        "הַיּוֹם שְׁנֵי יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁלוֹשָׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם אַרְבָּעָה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם חֲמִשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שִׁשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שִׁבְעָה יָמִים, שֶׁהֵם שָׁבֽוּעַ אֶחָד לָעֽוֹמֶר",
        "הַיּוֹם שְׁמוֹנָה יָמִים, שֶׁהֵם שָׁבֽוּעַ אֶחָד וְיוֹם אֶחָד לָעֽוֹמֶר",
        "הַיּוֹם תִּשְׁעָה יָמִים, שֶׁהֵם שָׁבֽוּעַ אֶחָד וּשְׁנֵי יָמִים לָעֽוֹמֶר",
        "הַיּוֹם עֲשָׂרָה יָמִים, שֶׁהֵם שָׁבֽוּעַ אֶחָד וּשְׁלוֹשָׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם אַחַד עָשָׂר יוֹם, שֶׁהֵם שָׁבֽוּעַ אֶחָד וְאַרְבָּעָה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁנֵים עָשָׂר יוֹם, שֶׁהֵם שָׁבֽוּעַ אֶחָד וַחֲמִשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁלוֹשָׁה עָשָׂר יוֹם, שֶׁהֵם שָׁבֽוּעַ אֶחָד וְשִׁשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם אַרְבָּעָה עָשָׂר יוֹם, שֶׁהֵם שְׁנֵי שָׁבוּעוֹת לָעֽוֹמֶר",
        "הַיּוֹם חֲמִשָּׁה עָשָׂר יוֹם, שֶׁהֵם שְׁנֵי שָׁבוּעוֹת וְיוֹם אֶחָד לָעֽוֹמֶר",
        "הַיּוֹם שִׁשָּׁה עָשָׂר יוֹם, שֶׁהֵם שְׁנֵי שָׁבוּעוֹת וּשְׁנֵי יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שִׁבְעָה עָשָׂר יוֹם, שֶׁהֵם שְׁנֵי שָׁבוּעוֹת וּשְׁלוֹשָׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁמוֹנָה עָשָׂר יוֹם, שֶׁהֵם שְׁנֵי שָׁבוּעוֹת וְאַרְבָּעָה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם תִּשְׁעָה עָשָׂר יוֹם, שֶׁהֵם שְׁנֵי שָׁבוּעוֹת וַחֲמִשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם עֶשְׂרִים יוֹם, שֶׁהֵם שְׁנֵי שָׁבוּעוֹת וְשִׁשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם אֶחָד וְעֶשְׂרִים יוֹם, שֶׁהֵם שְׁלוֹשָׁה שָׁבוּעוֹת לָעֽוֹמֶר",
        "הַיּוֹם שְׁנַיִם וְעֶשְׂרִים יוֹם, שֶׁהֵם שְׁלוֹשָׁה שָׁבוּעוֹת וְיוֹם אֶחָד לָעֽוֹמֶר",
        "הַיּוֹם שְׁלוֹשָׁה וְעֶשְׂרִים יוֹם, שֶׁהֵם שְׁלוֹשָׁה שָׁבוּעוֹת וּשְׁנֵי יָמִים לָעֽוֹמֶר",
        "הַיּוֹם אַרְבָּעָה וְעֶשְׂרִים יוֹם, שֶׁהֵם שְׁלוֹשָׁה שָׁבוּעוֹת וּשְׁלוֹשָׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם חֲמִשָּׁה וְעֶשְׂרִים יוֹם, שֶׁהֵם שְׁלוֹשָׁה שָׁבוּעוֹת וְאַרְבָּעָה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שִׁשָּׁה וְעֶשְׂרִים יוֹם, שֶׁהֵם שְׁלוֹשָׁה שָׁבוּעוֹת וַחֲמִשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שִׁבְעָה וְעֶשְׂרִים יוֹם, שֶׁהֵם שְׁלוֹשָׁה שָׁבוּעוֹת וְשִׁשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁמוֹנָה וְעֶשְׂרִים יוֹם, שֶׁהֵם אַרְבָּעָה שָׁבוּעוֹת לָעֽוֹמֶר",
        "הַיּוֹם תִּשְׁעָה וְעֶשְׂרִים יוֹם, שֶׁהֵם אַרְבָּעָה שָׁבוּעוֹת וְיוֹם אֶחָד לָעֽוֹמֶר",
        "הַיּוֹם שְׁלוֹשִׁים יוֹם, שֶׁהֵם אַרְבָּעָה שָׁבוּעוֹת וּשְׁנֵי יָמִים לָעֽוֹמֶר",
        "הַיּוֹם אֶחָד וּשְׁלוֹשִׁים יוֹם, שֶׁהֵם אַרְבָּעָה שָׁבוּעוֹת וּשְׁלוֹשָׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁנַיִם וּשְׁלוֹשִׁים יוֹם, שֶׁהֵם אַרְבָּעָה שָׁבוּעוֹת וְאַרְבָּעָה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁלוֹשָׁה וּשְׁלוֹשִׁים יוֹם, שֶׁהֵם אַרְבָּעָה שָׁבוּעוֹת וַחֲמִשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם אַרְבָּעָה וּשְׁלוֹשִׁים יוֹם, שֶׁהֵם אַרְבָּעָה שָׁבוּעוֹת וְשִׁשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם חֲמִשָּׁה וּשְׁלוֹשִׁים יוֹם, שֶׁהֵם חֲמִשָּׁה שָׁבוּעוֹת לָעֽוֹמֶר",
        "הַיּוֹם שִׁשָּׁה וּשְׁלוֹשִׁים יוֹם, שֶׁהֵם חֲמִשָּׁה שָׁבוּעוֹת וְיוֹם אֶחָד לָעֽוֹמֶר",
        "הַיּוֹם שִׁבְעָה וּשְׁלוֹשִׁים יוֹם, שֶׁהֵם חֲמִשָּׁה שָׁבוּעוֹת וּשְׁנֵי יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁמוֹנָה וּשְׁלוֹשִׁים יוֹם, שֶׁהֵם חֲמִשָּׁה שָׁבוּעוֹת וּשְׁלוֹשָׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם תִּשְׁעָה וּשְׁלוֹשִׁים יוֹם, שֶׁהֵם חֲמִשָּׁה שָׁבוּעוֹת וְאַרְבָּעָה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם אַרְבָּעִים יוֹם, שֶׁהֵם חֲמִשָּׁה שָׁבוּעוֹת וַחֲמִשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם אֶחָד וְאַרְבָּעִים יוֹם, שֶׁהֵם חֲמִשָּׁה שָׁבוּעוֹת וְשִׁשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁנַיִם וְאַרְבָּעִים יוֹם, שֶׁהֵם שִׁשָּׁה שָׁבוּעוֹת לָעֽוֹמֶר",
        "הַיּוֹם שְׁלוֹשָׁה וְאַרְבָּעִים יוֹם, שֶׁהֵם שִׁשָּׁה שָׁבוּעוֹת וְיוֹם אֶחָד לָעֽוֹמֶר",
        "הַיּוֹם אַרְבָּעָה וְאַרְבָּעִים יוֹם, שֶׁהֵם שִׁשָּׁה שָׁבוּעוֹת וּשְׁנֵי יָמִים לָעֽוֹמֶר",
        "הַיּוֹם חֲמִשָּׁה וְאַרְבָּעִים יוֹם, שֶׁהֵם שִׁשָּׁה שָׁבוּעוֹת וּשְׁלוֹשָׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שִׁשָּׁה וְאַרְבָּעִים יוֹם, שֶׁהֵם שִׁשָּׁה שָׁבוּעוֹת וְאַרְבָּעָה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שִׁבְעָה וְאַרְבָּעִים יוֹם, שֶׁהֵם שִׁשָּׁה שָׁבוּעוֹת וַחֲמִשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם שְׁמוֹנָה וְאַרְבָּעִים יוֹם, שֶׁהֵם שִׁשָּׁה שָׁבוּעוֹת וְשִׁשָּׁה יָמִים לָעֽוֹמֶר",
        "הַיּוֹם תִּשְׁעָה וְאַרְבָּעִים יוֹם, שֶׁהֵם שִׁבְעָה שָׁבוּעוֹת לָעֽוֹמֶר",
    ]
    /// `getTodayIs(lang: .he)`
    static let todayHeNN: [String] = [
        "היום יום אחד לעומר",
        "היום שני ימים לעומר",
        "היום שלושה ימים לעומר",
        "היום ארבעה ימים לעומר",
        "היום חמשה ימים לעומר",
        "היום ששה ימים לעומר",
        "היום שבעה ימים, שהם שבוע אחד לעומר",
        "היום שמונה ימים, שהם שבוע אחד ויום אחד לעומר",
        "היום תשעה ימים, שהם שבוע אחד ושני ימים לעומר",
        "היום עשרה ימים, שהם שבוע אחד ושלושה ימים לעומר",
        "היום אחד עשר יום, שהם שבוע אחד וארבעה ימים לעומר",
        "היום שנים עשר יום, שהם שבוע אחד וחמשה ימים לעומר",
        "היום שלושה עשר יום, שהם שבוע אחד וששה ימים לעומר",
        "היום ארבעה עשר יום, שהם שני שבועות לעומר",
        "היום חמשה עשר יום, שהם שני שבועות ויום אחד לעומר",
        "היום ששה עשר יום, שהם שני שבועות ושני ימים לעומר",
        "היום שבעה עשר יום, שהם שני שבועות ושלושה ימים לעומר",
        "היום שמונה עשר יום, שהם שני שבועות וארבעה ימים לעומר",
        "היום תשעה עשר יום, שהם שני שבועות וחמשה ימים לעומר",
        "היום עשרים יום, שהם שני שבועות וששה ימים לעומר",
        "היום אחד ועשרים יום, שהם שלושה שבועות לעומר",
        "היום שנים ועשרים יום, שהם שלושה שבועות ויום אחד לעומר",
        "היום שלושה ועשרים יום, שהם שלושה שבועות ושני ימים לעומר",
        "היום ארבעה ועשרים יום, שהם שלושה שבועות ושלושה ימים לעומר",
        "היום חמשה ועשרים יום, שהם שלושה שבועות וארבעה ימים לעומר",
        "היום ששה ועשרים יום, שהם שלושה שבועות וחמשה ימים לעומר",
        "היום שבעה ועשרים יום, שהם שלושה שבועות וששה ימים לעומר",
        "היום שמונה ועשרים יום, שהם ארבעה שבועות לעומר",
        "היום תשעה ועשרים יום, שהם ארבעה שבועות ויום אחד לעומר",
        "היום שלושים יום, שהם ארבעה שבועות ושני ימים לעומר",
        "היום אחד ושלושים יום, שהם ארבעה שבועות ושלושה ימים לעומר",
        "היום שנים ושלושים יום, שהם ארבעה שבועות וארבעה ימים לעומר",
        "היום שלושה ושלושים יום, שהם ארבעה שבועות וחמשה ימים לעומר",
        "היום ארבעה ושלושים יום, שהם ארבעה שבועות וששה ימים לעומר",
        "היום חמשה ושלושים יום, שהם חמשה שבועות לעומר",
        "היום ששה ושלושים יום, שהם חמשה שבועות ויום אחד לעומר",
        "היום שבעה ושלושים יום, שהם חמשה שבועות ושני ימים לעומר",
        "היום שמונה ושלושים יום, שהם חמשה שבועות ושלושה ימים לעומר",
        "היום תשעה ושלושים יום, שהם חמשה שבועות וארבעה ימים לעומר",
        "היום ארבעים יום, שהם חמשה שבועות וחמשה ימים לעומר",
        "היום אחד וארבעים יום, שהם חמשה שבועות וששה ימים לעומר",
        "היום שנים וארבעים יום, שהם ששה שבועות לעומר",
        "היום שלושה וארבעים יום, שהם ששה שבועות ויום אחד לעומר",
        "היום ארבעה וארבעים יום, שהם ששה שבועות ושני ימים לעומר",
        "היום חמשה וארבעים יום, שהם ששה שבועות ושלושה ימים לעומר",
        "היום ששה וארבעים יום, שהם ששה שבועות וארבעה ימים לעומר",
        "היום שבעה וארבעים יום, שהם ששה שבועות וחמשה ימים לעומר",
        "היום שמונה וארבעים יום, שהם ששה שבועות וששה ימים לעומר",
        "היום תשעה וארבעים יום, שהם שבעה שבועות לעומר",
    ]
    /// `getEmoji()`
    static let emoji: [String] = [
        "①",
        "②",
        "③",
        "④",
        "⑤",
        "⑥",
        "⑦",
        "⑧",
        "⑨",
        "⑩",
        "⑪",
        "⑫",
        "⑬",
        "⑭",
        "⑮",
        "⑯",
        "⑰",
        "⑱",
        "⑲",
        "⑳",
        "㉑",
        "㉒",
        "㉓",
        "㉔",
        "㉕",
        "㉖",
        "㉗",
        "㉘",
        "㉙",
        "㉚",
        "㉛",
        "㉜",
        "㉝",
        "㉞",
        "㉟",
        "㊱",
        "㊲",
        "㊳",
        "㊴",
        "㊵",
        "㊶",
        "㊷",
        "㊸",
        "㊹",
        "㊺",
        "㊻",
        "㊼",
        "㊽",
        "㊾",
    ]
    /// `getLamnatzeachWord()`
    static let word: [String] = [
        "אֱלֹהִים",
        "יְחָנֵּנוּ",
        "וִיבָרְכֵנוּ",
        "יָאֵר",
        "פָּנָיו",
        "אִתָּנוּ",
        "סֶלָה",
        "לָדַעַת",
        "בָּאָרֶץ",
        "דַּרְכֶּךָ",
        "בְּכָל",
        "גּוֹיִם",
        "יְשׁוּעָתֶךָ",
        "יוֹדוּךָ",
        "עַמִּים",
        "אֱלֹהִים",
        "יוֹדוּךָ",
        "עַמִּים",
        "כֻּלָּם",
        "יִשְׂמְחוּ",
        "וִירַנְּנוּ",
        "לְאֻמִּים",
        "כִּי",
        "תִשְׁפֹּט",
        "עַמִּים",
        "מִישׁוֹר",
        "וּלְאֻמִּים",
        "בָּאָרֶץ",
        "תַּנחֵם",
        "סֶלָה",
        "יוֹדוּךָ",
        "עַמִּים",
        "אֱלֹהִים",
        "יוֹדוּךָ",
        "עַמִּים",
        "כֻּלָּם",
        "אֶרֶץ",
        "נָתְנָה",
        "יְבוּלָהּ",
        "יְבָרְכֵנוּ",
        "אֱלֹהִים",
        "אֱלֹהֵינוּ",
        "יְבָרְכֵנוּ",
        "אֱלֹהִים",
        "וְיִירְאוּ",
        "אוֹתוֹ",
        "כָּל",
        "אַפְסֵי",
        "אָרֶץ",
    ]
    /// `getLamnatzeachLetter()`
    static let letter: [String] = [
        "י",
        "ש",
        "מ",
        "ח",
        "ו",
        "ו",
        "י",
        "ר",
        "נ",
        "נ",
        "ו",
        "ל",
        "א",
        "מ",
        "י",
        "ם",
        "כ",
        "י",
        "ת",
        "ש",
        "פ",
        "ו",
        "ט",
        "ע",
        "מ",
        "י",
        "ם",
        "מ",
        "י",
        "ש",
        "ו",
        "ר",
        "ו",
        "ל",
        "א",
        "מ",
        "י",
        "ם",
        "ב",
        "א",
        "ר",
        "ץ",
        "ת",
        "נ",
        "ח",
        "ם",
        "ס",
        "ל",
        "ה",
    ]
    /// `getAnaBekoachWord()`
    static let ana: [String] = [
        "אָנָּא",
        "בְּכֹחַ",
        "גְּדֻלַּת",
        "יְמִינְךָ",
        "תַּתִּיר",
        "צְרוּרָה",
        "אב״ג ית״ץ",
        "קַבֵּל",
        "רִנַּת",
        "עַמְּךָ",
        "שַׂגְּבֵנוּ",
        "טַהֲרֵנוּ",
        "נוֹרָא",
        "קר״ע שט״ן",
        "נָא",
        "גִבּוֹר",
        "דּוֹרְשֵׁי",
        "יִחוּדְךָ",
        "כְּבָבַת",
        "שָׁמְרֵם",
        "נג״ד יכ״ש",
        "בָּרְכֵם",
        "טַהֲרֵם",
        "רַחֲמֵי",
        "צִדְקָתְךָ",
        "תָּמִיד",
        "גָּמְלֵם",
        "בט״ר צת״ג",
        "חֲסִין",
        "קָדוֹשׁ",
        "בְּרֹב",
        "טוּבְךָ",
        "נַהֵל",
        "עֲדָתֶךָ",
        "חק״ב תנ״ע",
        "יָחִיד",
        "גֵּאֶה",
        "לְעַמְּךָ",
        "פְּנֵה",
        "זוֹכְרֵי",
        "קְדֻשָּׁתֶךָ",
        "יג״ל פז״ק",
        "שַׁוְעָתֵנוּ",
        "קַבֵּל",
        "וּשְׁמַע",
        "צַעֲקָתֵנוּ",
        "יוֹדֵעַ",
        "תַּעֲלוּמוֹת",
        "שק״ו צי״ת",
    ]
    static let weeks: [Int] = [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7]
    static let daysWithinWeeks: [Int] = [1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]
}
