import Foundation
import Testing
@testable import Hebcal

// Expected values were generated by @hebcal/core (hebcal-es6), e.g.
//   const z = new Zmanim(new GeoLocation(null, lat, lon, 0, tzid), date, false);
//   z.sunsetOffset(-18, true);               // candle lighting
//   z.sunsetOffset(42, true);                // Havdalah, minutes
//   Zmanim.roundTime(z.tzeit(8.5));          // Havdalah, degrees
// The Swift implementation should agree to within one minute.
struct ZmanimTests {

    let iso = ISO8601DateFormatter()

    struct Place {
        let latitude: Double
        let longitude: Double
        let timeZone: TimeZone

        init(_ latitude: Double, _ longitude: Double, _ tzid: String) {
            self.latitude = latitude
            self.longitude = longitude
            self.timeZone = TimeZone(identifier: tzid)!
        }
    }

    let newYork = Place(40.7128, -74.0060, "America/New_York")
    let jerusalem = Place(31.7683, 35.2137, "Asia/Jerusalem")
    let london = Place(51.5074, -0.1278, "Europe/London")
    let sydney = Place(-33.8679, 151.2073, "Australia/Sydney")
    let losAngeles = Place(34.0522, -118.2437, "America/Los_Angeles")
    let helsinki = Place(60.1695, 24.9354, "Europe/Helsinki")
    let tromso = Place(69.6492, 18.9553, "Europe/Oslo")
    let alert = Place(82.5, -62.35, "America/Toronto")

    // Noon on the given date in the place's time zone
    func date(_ year: Int, _ month: Int, _ day: Int, _ place: Place) -> Date {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = place.timeZone
        return calendar.date(from: DateComponents(year: year, month: month, day: day, hour: 12))!
    }

    func candleLighting(_ place: Place, _ date: Date, minutesBeforeSunset: Int = 18) -> Date? {
        return Zmanim.getCandleLightingTime(for: date, latitude: place.latitude, longitude: place.longitude,
                                            timeZone: place.timeZone, minutesBeforeSunset: minutesBeforeSunset)
    }

    func havdalah(_ place: Place, _ date: Date, _ opinion: HavdalahOpinion) -> Date? {
        return Zmanim.getHavdalahTime(for: date, latitude: place.latitude, longitude: place.longitude,
                                      timeZone: place.timeZone, opinion: opinion)
    }

    func assertTime(_ actual: Date?, _ expected: String, sourceLocation: SourceLocation = #_sourceLocation) {
        guard let actual = actual else {
            Issue.record("Expected \(expected), got nil", sourceLocation: sourceLocation)
            return
        }
        let expectedDate = iso.date(from: expected)!
        #expect(Swift.abs(actual.timeIntervalSince(expectedDate)) <= 60,
                "Actual: \(iso.string(from: actual)), Expected: \(expected)", sourceLocation: sourceLocation)
    }

    // MARK: - Candle Lighting Tests

    @Test func candleLighting_NewYork() {
        // Sunset 16:29:20 EST; 18 minutes before, seconds discarded
        assertTime(candleLighting(newYork, date(2023, 12, 1, newYork)), "2023-12-01T16:11:00-05:00")
    }

    @Test func candleLighting_Jerusalem() {
        // Sunset 16:35:02 IST; 40 minutes before
        assertTime(candleLighting(jerusalem, date(2023, 12, 1, jerusalem), minutesBeforeSunset: 40), "2023-12-01T15:55:00+02:00")
    }

    @Test func candleLighting_NegativeMinutesBeforeSunset() {
        // Sign is ignored: -40 is treated the same as 40
        assertTime(candleLighting(jerusalem, date(2023, 12, 1, jerusalem), minutesBeforeSunset: -40), "2023-12-01T15:55:00+02:00")
    }

    @Test func candleLighting_London() {
        assertTime(candleLighting(london, date(2023, 12, 1, london)), "2023-12-01T15:37:00Z")
    }

    @Test func candleLighting_SouthernHemisphere() {
        assertTime(candleLighting(sydney, date(2024, 1, 5, sydney)), "2024-01-05T19:51:00+11:00")
    }

    @Test func candleLighting_Summer() {
        assertTime(candleLighting(losAngeles, date(2024, 6, 21, losAngeles)), "2024-06-21T19:49:00-07:00")
        assertTime(candleLighting(helsinki, date(2024, 6, 22, helsinki)), "2024-06-22T22:32:00+03:00")
    }

    @Test func candleLighting_DateIsLocalToTimeZone() {
        // 11pm EST on Dec 1 is already Dec 2 in UTC; the local date must be used
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = newYork.timeZone
        let lateEvening = calendar.date(from: DateComponents(year: 2023, month: 12, day: 1, hour: 23))!
        assertTime(candleLighting(newYork, lateEvening), "2023-12-01T16:11:00-05:00")
    }

    @Test func candleLighting_Arctic_NoSunset() {
        // Alert, Nunavut on June 1 is polar day
        #expect(candleLighting(alert, date(2023, 6, 1, alert)) == nil, "Candle lighting time should be nil during polar day.")
    }

    @Test func candleLighting_PolarNight_NoSunset() {
        #expect(candleLighting(tromso, date(2023, 12, 2, tromso)) == nil, "Candle lighting time should be nil during polar night.")
    }

    // MARK: - Havdalah Tests

    @Test func havdalah_NewYork_42Minutes() {
        // Sunset 16:29:05 EST; seconds < 30 so no round up
        assertTime(havdalah(newYork, date(2023, 12, 2, newYork), .minutesAfterSunset(minutes: 42)), "2023-12-02T17:11:00-05:00")
    }

    @Test func havdalah_NewYork_72Minutes() {
        assertTime(havdalah(newYork, date(2023, 12, 2, newYork), .minutesAfterSunset(minutes: 72)), "2023-12-02T17:41:00-05:00")
    }

    @Test func havdalah_Minutes_RoundsUp() {
        // Sydney sunset 20:09:53 AEDT; seconds >= 30 round up to the next minute
        assertTime(havdalah(sydney, date(2024, 1, 5, sydney), .minutesAfterSunset(minutes: 42)), "2024-01-05T20:52:00+11:00")
        // Helsinki sunset 22:50:15 EEST; Havdalah is after local midnight
        assertTime(havdalah(helsinki, date(2024, 6, 22, helsinki), .minutesAfterSunset(minutes: 72)), "2024-06-23T00:02:00+03:00")
    }

    @Test func havdalah_NewYork_Degrees8_5() {
        assertTime(havdalah(newYork, date(2023, 12, 2, newYork), .degreesBelowHorizon(angle: 8.5)), "2023-12-02T17:14:00-05:00")
    }

    @Test func havdalah_Degrees() {
        assertTime(havdalah(jerusalem, date(2023, 12, 1, jerusalem), .degreesBelowHorizon(angle: 8.5)), "2023-12-01T17:14:00+02:00")
        assertTime(havdalah(london, date(2023, 12, 1, london), .degreesBelowHorizon(angle: 8.5)), "2023-12-01T16:52:00Z")
        assertTime(havdalah(sydney, date(2024, 1, 5, sydney), .degreesBelowHorizon(angle: 8.5)), "2024-01-05T20:53:00+11:00")
        assertTime(havdalah(losAngeles, date(2024, 6, 21, losAngeles), .degreesBelowHorizon(angle: 7.083)), "2024-06-21T20:43:00-07:00")
    }

    @Test func havdalah_Degrees_NegativeAngle() {
        // A negative angle is treated as below the horizon
        assertTime(havdalah(newYork, date(2023, 12, 2, newYork), .degreesBelowHorizon(angle: -8.5)), "2023-12-02T17:14:00-05:00")
    }

    @Test func havdalah_Degrees_WhiteNight() {
        // Helsinki near the summer solstice: the sun never gets 8.5° below the horizon
        #expect(havdalah(helsinki, date(2024, 6, 22, helsinki), .degreesBelowHorizon(angle: 8.5)) == nil)
    }

    @Test func havdalah_Degrees_Tromso_PolarNight() {
        // Tromsø on Dec 2 has no sunrise or sunset, but the sun still climbs to about 2° below the horizon
        // at midday, so it crosses 8.5° below the horizon in the afternoon
        #expect(havdalah(tromso, date(2023, 12, 2, tromso), .minutesAfterSunset(minutes: 42)) == nil)
        assertTime(havdalah(tromso, date(2023, 12, 2, tromso), .degreesBelowHorizon(angle: 8.5)), "2023-12-02T14:58:00+01:00")
    }

    // MARK: - Rounding

    @Test func sunsetOffsetRounding() {
        let sunset = iso.date(from: "2023-12-01T21:29:31Z")!
        #expect(Zmanim.sunsetOffset(sunset, minutes: -18) == iso.date(from: "2023-12-01T21:11:00Z"))
        #expect(Zmanim.sunsetOffset(sunset, minutes: 42) == iso.date(from: "2023-12-01T22:12:00Z"))
    }

    @Test func roundTime() {
        #expect(Zmanim.roundTime(iso.date(from: "2023-12-01T22:13:29Z")!.addingTimeInterval(0.9)) == iso.date(from: "2023-12-01T22:13:00Z"))
        #expect(Zmanim.roundTime(iso.date(from: "2023-12-01T22:13:30Z")!) == iso.date(from: "2023-12-01T22:14:00Z"))
    }
}
